import { ReduxProvider } from '@/redux/provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Advertise Table',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container mx-auto'>
          <div className='h-14 bg-white rounded-lg flex justify-between items-center'>
            <Link href="/"><button className='w-[426px] h-10 rounded-lg px-4 py-2 bg-[#F9F9F9]'>Kampanyalar</button></Link>         
            <Link href="/ad-groups"><button className='w-[426px] h-10 rounded-lg px-4 py-2 bg-[#F9F9F9]'>Reklam Grupları</button></Link>
            <Link href="/ads"><button className='w-[426px] h-10 rounded-lg px-4 py-2 bg-[#F9F9F9]'>Reklamlar</button></Link>     
            </div>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </div>

      </body>
    </html>
  )
}
